# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5436636c2d54221c31a17a0952d6fa1aa160a5c96558331f7da986510b7dbf3be5d1c9c0e045757988812a246d6a0069ee16b6ca218a4d431645a23f0369d061

test:
  secret_key_base: 2212100b461b06f96d1a57c11be6729d3344d3f8459e0cdd080ae3a6fe210a517244e29bfeb89be575aa81d261486cdc7b63b1a611447ae7c9dc78386c1b2706

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
